# Generated by Django 4.2.6 on 2023-10-20 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('80285add-6f60-48c1-b57d-8f56827021a2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('80285add-6f60-48c1-b57d-8f56827021a2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('80285add-6f60-48c1-b57d-8f56827021a2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
